version: '3'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/data  

  # nestbackend:
  #  build: .   
  #  depends_on:
  #   - postgres   
